# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAnnonceeleve():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_annonceeleve(self):
    self.driver.get("https://www.superprof.fr/")
    self.driver.set_window_size(1280, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".static-content .avatar-wrapper").click()
    self.driver.find_element(By.LINK_TEXT, "Annonces").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Voir en tant qu\'élève").click()
    self.vars["win2548"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win2548"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["undefined"])
  
