# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConnexion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_connexion(self):
    self.driver.get("https://www.superprof.fr/")
    self.driver.set_window_size(1280, 680)
    self.driver.find_element(By.CSS_SELECTOR, ".static-content .basic-header-button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".focus > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".focus > input").send_keys("russe.avec.olessia@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".focus > input").send_keys("Kiev2022")
    self.driver.find_element(By.CSS_SELECTOR, ".focus > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".focus > input").send_keys("russe.avec.olessia+11@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".signin .buttons-container > .big-button").click()
  
